/**
 * Generated by @openapi-codegen
 *
 * @version 2.0.0
 */
import type * as Fetcher from "./gatlingEnterpriseFetcher.js";
import {
  gatlingEnterpriseFetch,
  GatlingEnterpriseFetcherExtraProps
} from "./gatlingEnterpriseFetcher.js";
import type * as Schemas from "./gatlingEnterpriseSchemas.js";

export type ApiTokenReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type ApiTokenReadAllVariables = GatlingEnterpriseFetcherExtraProps;

/**
 * List all the API Tokens that can be seen by the API token.
 *
 * Require the `Administrate` role at the global level or on a team to see its tokens; others are omitted.
 */
export const apiTokenReadAll = (variables: ApiTokenReadAllVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.ApiTokenReadAllResponse,
    ApiTokenReadAllError,
    undefined,
    {},
    {},
    {}
  >({ url: "/v2/api-tokens", method: "get", ...variables, signal });

export type ApiTokenCreateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type ApiTokenCreateOneVariables = {
  body: Schemas.ApiTokenRequest;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Create a new API Token.
 *
 * Require the `Administrate` role at the global level or on each target team.
 */
export const apiTokenCreateOne = (variables: ApiTokenCreateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.ApiTokenCreateOneResponse,
    ApiTokenCreateOneError,
    Schemas.ApiTokenRequest,
    {},
    {},
    {}
  >({ url: "/v2/api-tokens", method: "post", ...variables, signal });

export type ApiTokenDeleteOnePathParams = {
  /**
   * API Token ID
   */
  apiTokenId: string;
};

export type ApiTokenDeleteOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type ApiTokenDeleteOneVariables = {
  pathParams: ApiTokenDeleteOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Delete the specified API Token.
 *
 * Require the `Administrate` role at the global level or on the token's targeted teams.
 */
export const apiTokenDeleteOne = (variables: ApiTokenDeleteOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    undefined,
    ApiTokenDeleteOneError,
    undefined,
    {},
    {},
    ApiTokenDeleteOnePathParams
  >({
    url: "/v2/api-tokens/{apiTokenId}",
    method: "delete",
    ...variables,
    signal
  });

export type ApiTokenUpdateOnePathParams = {
  /**
   * API Token ID
   */
  apiTokenId: string;
};

export type ApiTokenUpdateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type ApiTokenUpdateOneVariables = {
  body: Schemas.ApiTokenRequest;
  pathParams: ApiTokenUpdateOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Update the details of the specified API Token.
 *
 * Require the `Administrate` role at the global level or on the token's targeted teams.
 */
export const apiTokenUpdateOne = (variables: ApiTokenUpdateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.ApiTokenUpdateOneResponse,
    ApiTokenUpdateOneError,
    Schemas.ApiTokenRequest,
    {},
    {},
    ApiTokenUpdateOnePathParams
  >({
    url: "/v2/api-tokens/{apiTokenId}",
    method: "put",
    ...variables,
    signal
  });

export type ApiTokenRegeneratePathParams = {
  /**
   * API Token ID
   */
  tokenId: string;
};

export type ApiTokenRegenerateError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type ApiTokenRegenerateVariables = {
  pathParams: ApiTokenRegeneratePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Regenerate the specified API Token.
 *
 * Require the `Administrate` role at the global level or on the token's targeted teams.
 */
export const apiTokenRegenerate = (variables: ApiTokenRegenerateVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.ApiTokenCreateOneResponse,
    ApiTokenRegenerateError,
    undefined,
    {},
    {},
    ApiTokenRegeneratePathParams
  >({
    url: "/v2/api-tokens/{tokenId}/regenerate-token",
    method: "post",
    ...variables,
    signal
  });

export type InfoReadError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type InfoReadVariables = GatlingEnterpriseFetcherExtraProps;

/**
 * Get the server information.
 *
 * No permission, no authentication required.
 */
export const infoRead = (variables: InfoReadVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<Schemas.InfoReadResponse, InfoReadError, undefined, {}, {}, {}>({
    url: "/v2/info",
    method: "get",
    ...variables,
    signal
  });

export type LocationReadAllQueryParams = {
  ["artifact-format"]?: Schemas.ArtifactFormatEnum;
  type?: Schemas.LocationTypeEnum;
};

export type LocationReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type LocationReadAllVariables = {
  queryParams?: LocationReadAllQueryParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * List all the locations that can be seen by the API token.
 *
 * Require at least the `Read` role on any team.
 */
export const locationReadAll = (variables: LocationReadAllVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.LocationReadAllResponse,
    LocationReadAllError,
    undefined,
    {},
    LocationReadAllQueryParams,
    {}
  >({ url: "/v2/locations", method: "get", ...variables, signal });

export type PackageReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type PackageReadAllVariables = GatlingEnterpriseFetcherExtraProps;

/**
 * List all the packages that can be seen by the API token.
 *
 * Require at least the `Read` role on a team to see its packages; others are omitted.
 */
export const packageReadAll = (variables: PackageReadAllVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.PackageReadAllResponse,
    PackageReadAllError,
    undefined,
    {},
    {},
    {}
  >({ url: "/v2/packages", method: "get", ...variables, signal });

export type PackageCreateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type PackageCreateOneVariables = {
  body: Schemas.PackageCreateOneRequest;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Create a new package.
 *
 * Require the `Configure` role on the target team.
 * Require the Managed Package feature to be enabled on the organization when creating a managed package.
 */
export const packageCreateOne = (variables: PackageCreateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.PackageCreateOneResponse,
    PackageCreateOneError,
    Schemas.PackageCreateOneRequest,
    {},
    {},
    {}
  >({ url: "/v2/packages", method: "post", ...variables, signal });

export type PackageDeleteOnePathParams = {
  /**
   * Package ID
   */
  packageId: string;
};

export type PackageDeleteOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type PackageDeleteOneVariables = {
  pathParams: PackageDeleteOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Delete the specified package.
 *
 * Require the `Configure` role on the package's team.
 */
export const packageDeleteOne = (variables: PackageDeleteOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    undefined,
    PackageDeleteOneError,
    undefined,
    {},
    {},
    PackageDeleteOnePathParams
  >({
    url: "/v2/packages/{packageId}",
    method: "delete",
    ...variables,
    signal
  });

export type PackageReadOnePathParams = {
  /**
   * Package ID
   */
  packageId: string;
};

export type PackageReadOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type PackageReadOneVariables = {
  pathParams: PackageReadOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the details of the specified package.
 *
 * Require the `Read` role on the package's team.
 */
export const packageReadOne = (variables: PackageReadOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.PackageReadOneResponse,
    PackageReadOneError,
    undefined,
    {},
    {},
    PackageReadOnePathParams
  >({ url: "/v2/packages/{packageId}", method: "get", ...variables, signal });

export type PackageUpdateOnePathParams = {
  /**
   * Package ID
   */
  packageId: string;
};

export type PackageUpdateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type PackageUpdateOneVariables = {
  body: Schemas.PackageRequest;
  pathParams: PackageUpdateOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Update the details of the specified package.
 *
 * Require the `Configure` role on the package's team.
 */
export const packageUpdateOne = (variables: PackageUpdateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.PackageUpdateOneResponse,
    PackageUpdateOneError,
    Schemas.PackageRequest,
    {},
    {},
    PackageUpdateOnePathParams
  >({ url: "/v2/packages/{packageId}", method: "put", ...variables, signal });

export type RunReadAllQueryParams = {
  /**
   * @format date-time
   */
  ["updated-at_gt"]?: string;
  /**
   * @minimum 1
   * @format int32
   */
  limit?: number;
  ["test-id"]?: string[];
};

export type RunReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type RunReadAllVariables = {
  queryParams?: RunReadAllQueryParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * List all the Runs updated since the provided timestamp (default: 24h).
 *
 * Require at least the `Read` role on the run's simulation's team; others are omitted.
 */
export const runReadAll = (variables: RunReadAllVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.RunReadAllResponse,
    RunReadAllError,
    undefined,
    {},
    RunReadAllQueryParams,
    {}
  >({ url: "/v2/runs", method: "get", ...variables, signal });

export type RunReadOnePathParams = {
  /**
   * Run ID
   */
  runId: string;
};

export type RunReadOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type RunReadOneVariables = {
  pathParams: RunReadOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the details of the specified Run.
 *
 * Require the `Read` role on the run's simulation's team.
 */
export const runReadOne = (variables: RunReadOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.RunReadOneResponse,
    RunReadOneError,
    undefined,
    {},
    {},
    RunReadOnePathParams
  >({ url: "/v2/runs/{runId}", method: "get", ...variables, signal });

export type RunUpdateOnePathParams = {
  /**
   * Run ID
   */
  runId: string;
};

export type RunUpdateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type RunUpdateOneVariables = {
  body?: Schemas.RunRequest;
  pathParams: RunUpdateOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Update the details of the specified Run.
 *
 * Require the `Start` role on the run's simulation's team.
 */
export const runUpdateOne = (variables: RunUpdateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.RunUpdateOneResponse,
    RunUpdateOneError,
    Schemas.RunRequest,
    {},
    {},
    RunUpdateOnePathParams
  >({ url: "/v2/runs/{runId}", method: "put", ...variables, signal });

export type RunPublicLinkCreateOnePathParams = {
  /**
   * Run ID
   */
  runId: string;
};

export type RunPublicLinkCreateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type RunPublicLinkCreateOneVariables = {
  body: Schemas.RunPublicLinkRequest;
  pathParams: RunPublicLinkCreateOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Create a public link for the specified Run.
 *
 * The link allows unauthenticated access to the run's dashboard until it expires.
 * Require the `Start` role on the run's simulation's team.
 */
export const runPublicLinkCreateOne = (
  variables: RunPublicLinkCreateOneVariables,
  signal?: AbortSignal
) =>
  gatlingEnterpriseFetch<
    Schemas.RunPublicLinkCreateOneResponse,
    RunPublicLinkCreateOneError,
    Schemas.RunPublicLinkRequest,
    {},
    {},
    RunPublicLinkCreateOnePathParams
  >({
    url: "/v2/runs/{runId}/actions/create-public-link",
    method: "post",
    ...variables,
    signal
  });

export type RunStopOnePathParams = {
  /**
   * Run ID
   */
  runId: string;
};

export type RunStopOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type RunStopOneVariables = {
  pathParams: RunStopOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Stop the specified Run.
 *
 * Require the `Start` role on the run's simulation's team.
 */
export const runStopOne = (variables: RunStopOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<undefined, RunStopOneError, undefined, {}, {}, RunStopOnePathParams>({
    url: "/v2/runs/{runId}/actions/stop",
    method: "post",
    ...variables,
    signal
  });

export type RunReadLogsPathParams = {
  /**
   * Run ID
   */
  runId: string;
};

export type RunReadLogsError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type RunReadLogsVariables = {
  pathParams: RunReadLogsPathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the logs of the specified Run.
 *
 * Require the `Read` role on the run's simulation's team.
 */
export const runReadLogs = (variables: RunReadLogsVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.RunReadLogsResponse,
    RunReadLogsError,
    undefined,
    {},
    {},
    RunReadLogsPathParams
  >({ url: "/v2/runs/{runId}/logs", method: "get", ...variables, signal });

export type RunViewReadReportGroupsPathParams = {
  /**
   * Run ID
   */
  runId: string;
};

export type RunViewReadReportGroupsQueryParams = {
  /**
   * Start of the time window, in seconds from run start. Defaults to 0.
   *
   * @minimum 0
   * @format int32
   */
  from?: number;
  /**
   * End of the time window, in seconds from run start. Defaults to run duration.
   *
   * @minimum 0
   * @format int32
   */
  to?: number;
  /**
   * Filter to a specific scenario. Omit to combine all scenarios.
   */
  scenario?: string;
};

export type RunViewReadReportGroupsError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type RunViewReadReportGroupsVariables = {
  pathParams: RunViewReadReportGroupsPathParams;
  queryParams?: RunViewReadReportGroupsQueryParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get per-group performance statistics for the specified Run.
 *
 * Returns the run's top-level groups; each group nests its sub-groups in
 * `children`. Stats cover the full run unless `from` and `to` are specified as
 * offsets in seconds from the run start.
 *
 * Require the `Read` role on the run's simulation's team.
 */
export const runViewReadReportGroups = (
  variables: RunViewReadReportGroupsVariables,
  signal?: AbortSignal
) =>
  gatlingEnterpriseFetch<
    Schemas.RunViewReadReportGroupsResponse,
    RunViewReadReportGroupsError,
    undefined,
    {},
    RunViewReadReportGroupsQueryParams,
    RunViewReadReportGroupsPathParams
  >({
    url: "/v2/runs/{runId}/views/report/groups",
    method: "get",
    ...variables,
    signal
  });

export type RunViewReadReportRequestsPathParams = {
  /**
   * Run ID
   */
  runId: string;
};

export type RunViewReadReportRequestsQueryParams = {
  /**
   * Start of the time window, in seconds from run start. Defaults to 0.
   *
   * @minimum 0
   * @format int32
   */
  from?: number;
  /**
   * End of the time window, in seconds from run start. Defaults to run duration.
   *
   * @minimum 0
   * @format int32
   */
  to?: number;
  /**
   * Filter to a specific scenario. Omit to combine all scenarios.
   */
  scenario?: string;
};

export type RunViewReadReportRequestsError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type RunViewReadReportRequestsVariables = {
  pathParams: RunViewReadReportRequestsPathParams;
  queryParams?: RunViewReadReportRequestsQueryParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get per-request performance statistics for the specified Run.
 *
 * Returns a tree: the root aggregates all requests, intermediate nodes are groups,
 * and leaf nodes are individual requests. Stats cover the full run unless `from`
 * and `to` are specified as offsets in seconds from the run start.
 *
 * Require the `Read` role on the run's simulation's team.
 */
export const runViewReadReportRequests = (
  variables: RunViewReadReportRequestsVariables,
  signal?: AbortSignal
) =>
  gatlingEnterpriseFetch<
    Schemas.RunViewReadReportRequestsResponse,
    RunViewReadReportRequestsError,
    undefined,
    {},
    RunViewReadReportRequestsQueryParams,
    RunViewReadReportRequestsPathParams
  >({
    url: "/v2/runs/{runId}/views/report/requests",
    method: "get",
    ...variables,
    signal
  });

export type SourceRepositoryReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SourceRepositoryReadAllVariables = GatlingEnterpriseFetcherExtraProps;

/**
 * List all the Source Repositories that can be seen by the API token.
 *
 * Require at least the `Read` role on a team to see its source repositories; others are omitted.
 */
export const sourceRepositoryReadAll = (
  variables: SourceRepositoryReadAllVariables,
  signal?: AbortSignal
) =>
  gatlingEnterpriseFetch<
    Schemas.SourceRepositoryReadAllResponse,
    SourceRepositoryReadAllError,
    undefined,
    {},
    {},
    {}
  >({ url: "/v2/source-repositories", method: "get", ...variables, signal });

export type SourceRepositoryCreateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SourceRepositoryCreateOneVariables = {
  body: Schemas.SourceRepositoryRequest;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Create a new Source Repository.
 *
 * Require the `Configure` role on the target team.
 */
export const sourceRepositoryCreateOne = (
  variables: SourceRepositoryCreateOneVariables,
  signal?: AbortSignal
) =>
  gatlingEnterpriseFetch<
    Schemas.SourceRepositoryCreateOneResponse,
    SourceRepositoryCreateOneError,
    Schemas.SourceRepositoryRequest,
    {},
    {},
    {}
  >({ url: "/v2/source-repositories", method: "post", ...variables, signal });

export type SourceRepositoryDeleteOnePathParams = {
  /**
   * Source Repository ID
   */
  sourceRepositoryId: string;
};

export type SourceRepositoryDeleteOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SourceRepositoryDeleteOneVariables = {
  pathParams: SourceRepositoryDeleteOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Delete the specified Source Repository.
 *
 * Require the `Configure` role on the source repository's team.
 */
export const sourceRepositoryDeleteOne = (
  variables: SourceRepositoryDeleteOneVariables,
  signal?: AbortSignal
) =>
  gatlingEnterpriseFetch<
    undefined,
    SourceRepositoryDeleteOneError,
    undefined,
    {},
    {},
    SourceRepositoryDeleteOnePathParams
  >({
    url: "/v2/source-repositories/{sourceRepositoryId}",
    method: "delete",
    ...variables,
    signal
  });

export type SourceRepositoryReadOnePathParams = {
  /**
   * Source Repository ID
   */
  sourceRepositoryId: string;
};

export type SourceRepositoryReadOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SourceRepositoryReadOneVariables = {
  pathParams: SourceRepositoryReadOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the details of the specified Source Repository.
 *
 * Require the `Read` role on the source repository's team.
 */
export const sourceRepositoryReadOne = (
  variables: SourceRepositoryReadOneVariables,
  signal?: AbortSignal
) =>
  gatlingEnterpriseFetch<
    Schemas.SourceRepositoryReadOneResponse,
    SourceRepositoryReadOneError,
    undefined,
    {},
    {},
    SourceRepositoryReadOnePathParams
  >({
    url: "/v2/source-repositories/{sourceRepositoryId}",
    method: "get",
    ...variables,
    signal
  });

export type SsoGroupReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SsoGroupReadAllVariables = GatlingEnterpriseFetcherExtraProps;

/**
 * List all the SSO Groups that can be seen by the API token.
 *
 * Require the `Administrate` role at the global level or on a team to see its SSO groups; others are omitted.
 */
export const ssoGroupReadAll = (variables: SsoGroupReadAllVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.SsoGroupReadAllResponse,
    SsoGroupReadAllError,
    undefined,
    {},
    {},
    {}
  >({ url: "/v2/sso-groups", method: "get", ...variables, signal });

export type SsoGroupCreateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SsoGroupCreateOneVariables = {
  body: Schemas.SsoGroupRequest;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Create a new SSO group.
 *
 * Require the `Administrate` role at the global level or on each target team.
 * Require the SSO Group Mapping feature to be enabled.
 */
export const ssoGroupCreateOne = (variables: SsoGroupCreateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.SsoGroupCreateOneResponse,
    SsoGroupCreateOneError,
    Schemas.SsoGroupRequest,
    {},
    {},
    {}
  >({ url: "/v2/sso-groups", method: "post", ...variables, signal });

export type SsoGroupDeleteOnePathParams = {
  /**
   * The ID of the SSO group mapping
   */
  ssoGroupId: string;
};

export type SsoGroupDeleteOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SsoGroupDeleteOneVariables = {
  pathParams: SsoGroupDeleteOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Delete the specified SSO group.
 *
 * Require the `Administrate` role at the global level or on the SSO group's targeted teams.
 */
export const ssoGroupDeleteOne = (variables: SsoGroupDeleteOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    undefined,
    SsoGroupDeleteOneError,
    undefined,
    {},
    {},
    SsoGroupDeleteOnePathParams
  >({
    url: "/v2/sso-groups/{ssoGroupId}",
    method: "delete",
    ...variables,
    signal
  });

export type SsoGroupReadOnePathParams = {
  /**
   * The ID of the SSO group mapping
   */
  ssoGroupId: string;
};

export type SsoGroupReadOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SsoGroupReadOneVariables = {
  pathParams: SsoGroupReadOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the details of the specified SSO group.
 *
 * Require the `Administrate` role at the global level or on the SSO group's teams.
 */
export const ssoGroupReadOne = (variables: SsoGroupReadOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.SsoGroupReadOneResponse,
    SsoGroupReadOneError,
    undefined,
    {},
    {},
    SsoGroupReadOnePathParams
  >({
    url: "/v2/sso-groups/{ssoGroupId}",
    method: "get",
    ...variables,
    signal
  });

export type SsoGroupUpdateOnePathParams = {
  /**
   * The ID of the SSO group mapping
   */
  ssoGroupId: string;
};

export type SsoGroupUpdateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type SsoGroupUpdateOneVariables = {
  body: Schemas.SsoGroupRequest;
  pathParams: SsoGroupUpdateOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Update the details of the specified SSO group.
 *
 * Require the `Administrate` role at the global level or on the SSO group's targeted teams.
 */
export const ssoGroupUpdateOne = (variables: SsoGroupUpdateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.SsoGroupUpdateOneResponse,
    SsoGroupUpdateOneError,
    Schemas.SsoGroupRequest,
    {},
    {},
    SsoGroupUpdateOnePathParams
  >({
    url: "/v2/sso-groups/{ssoGroupId}",
    method: "put",
    ...variables,
    signal
  });

export type TeamReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TeamReadAllVariables = GatlingEnterpriseFetcherExtraProps;

/**
 * List all the teams that can be seen by the API token.
 *
 * Require at least the `Read` role on a team to see it; others are omitted.
 */
export const teamReadAll = (variables: TeamReadAllVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<Schemas.TeamReadAllResponse, TeamReadAllError, undefined, {}, {}, {}>({
    url: "/v2/teams",
    method: "get",
    ...variables,
    signal
  });

export type TeamCreateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TeamCreateOneVariables = {
  body: Schemas.TeamRequest;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Create a new team.
 *
 * Require the `Administrate` role at the global level.
 */
export const teamCreateOne = (variables: TeamCreateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TeamCreateOneResponse,
    TeamCreateOneError,
    Schemas.TeamRequest,
    {},
    {},
    {}
  >({ url: "/v2/teams", method: "post", ...variables, signal });

export type TeamDeleteOnePathParams = {
  /**
   * Team ID
   */
  teamId: string;
};

export type TeamDeleteOneQueryParams = {
  /**
   * @default false
   */
  force: boolean;
};

export type TeamDeleteOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TeamDeleteOneVariables = {
  pathParams: TeamDeleteOnePathParams;
  queryParams: TeamDeleteOneQueryParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Delete the specified team.
 *
 * Require the `Administrate` role at the global level or on the team.
 */
export const teamDeleteOne = (variables: TeamDeleteOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    undefined,
    TeamDeleteOneError,
    undefined,
    {},
    TeamDeleteOneQueryParams,
    TeamDeleteOnePathParams
  >({ url: "/v2/teams/{teamId}", method: "delete", ...variables, signal });

export type TeamReadOnePathParams = {
  /**
   * Team ID
   */
  teamId: string;
};

export type TeamReadOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TeamReadOneVariables = {
  pathParams: TeamReadOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the details of the specified team.
 *
 * Require the `Read` role on the team.
 */
export const teamReadOne = (variables: TeamReadOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TeamReadOneResponse,
    TeamReadOneError,
    undefined,
    {},
    {},
    TeamReadOnePathParams
  >({ url: "/v2/teams/{teamId}", method: "get", ...variables, signal });

export type TeamLimitReadOnePathParams = {
  /**
   * Team ID
   */
  teamId: string;
};

export type TeamLimitReadOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TeamLimitReadOneVariables = {
  pathParams: TeamLimitReadOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the limits of the specified team.
 *
 * Require the `Administrate` role at the global level.
 */
export const teamLimitReadOne = (variables: TeamLimitReadOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TeamLimitReadOneResponse,
    TeamLimitReadOneError,
    undefined,
    {},
    {},
    TeamLimitReadOnePathParams
  >({ url: "/v2/teams/{teamId}/limits", method: "get", ...variables, signal });

export type TeamLimitUpdateOnePathParams = {
  /**
   * Team ID
   */
  teamId: string;
};

export type TeamLimitUpdateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TeamLimitUpdateOneVariables = {
  body?: Schemas.TeamLimitRequest;
  pathParams: TeamLimitUpdateOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Update the limits of the specified team.
 *
 * Require the `Administrate` role at the global level.
 */
export const teamLimitUpdateOne = (variables: TeamLimitUpdateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TeamLimitUpdateOneResponse,
    TeamLimitUpdateOneError,
    Schemas.TeamLimitRequest,
    {},
    {},
    TeamLimitUpdateOnePathParams
  >({ url: "/v2/teams/{teamId}/limits", method: "put", ...variables, signal });

export type TestReadAllQueryParams = {
  teamId?: string[];
  /**
   * @format date-time
   */
  ["updated-at_gt"]?: string;
};

export type TestReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TestReadAllVariables = {
  queryParams?: TestReadAllQueryParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * List all the tests that can be seen by the API token.
 *
 * Require at least the `Read` role on the team of the test's package or source repository; others are omitted.
 */
export const testReadAll = (variables: TestReadAllVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TestReadAllResponse,
    TestReadAllError,
    undefined,
    {},
    TestReadAllQueryParams,
    {}
  >({ url: "/v2/tests", method: "get", ...variables, signal });

export type TestCreateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TestCreateOneVariables = {
  body: Schemas.TestRequest;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Create a new test.
 *
 * Require the `Configure` role on the team of the referenced package or source repository.
 */
export const testCreateOne = (variables: TestCreateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TestCreateOneResponse,
    TestCreateOneError,
    Schemas.TestRequest,
    {},
    {},
    {}
  >({ url: "/v2/tests", method: "post", ...variables, signal });

export type TestDeleteOnePathParams = {
  /**
   * Test ID
   */
  testId: string;
};

export type TestDeleteOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TestDeleteOneVariables = {
  pathParams: TestDeleteOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Delete the specified test.
 *
 * Require the `Configure` role on the team of the test's package or source repository.
 */
export const testDeleteOne = (variables: TestDeleteOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<undefined, TestDeleteOneError, undefined, {}, {}, TestDeleteOnePathParams>(
    { url: "/v2/tests/{testId}", method: "delete", ...variables, signal }
  );

export type TestReadOnePathParams = {
  /**
   * Test ID
   */
  testId: string;
};

export type TestReadOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TestReadOneVariables = {
  pathParams: TestReadOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the details of the specified test.
 *
 * Require the `Read` role on the team of the test's package or source repository.
 */
export const testReadOne = (variables: TestReadOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TestReadOneResponse,
    TestReadOneError,
    undefined,
    {},
    {},
    TestReadOnePathParams
  >({ url: "/v2/tests/{testId}", method: "get", ...variables, signal });

export type TestUpdateOnePathParams = {
  /**
   * Test ID
   */
  testId: string;
};

export type TestUpdateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TestUpdateOneVariables = {
  body: Schemas.TestRequest;
  pathParams: TestUpdateOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Update the details of the specified test.
 *
 * Require the `Configure` role on the team of the test's package or source repository.
 */
export const testUpdateOne = (variables: TestUpdateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TestUpdateOneResponse,
    TestUpdateOneError,
    Schemas.TestRequest,
    {},
    {},
    TestUpdateOnePathParams
  >({ url: "/v2/tests/{testId}", method: "put", ...variables, signal });

export type TestStartOnePathParams = {
  /**
   * Test ID
   */
  testId: string;
};

export type TestStartOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type TestStartOneVariables = {
  body?: Schemas.TestStartOneRequest;
  pathParams: TestStartOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Start a run for the specified test.
 *
 * Require the `Start` role on the team of the test's package or source repository.
 */
export const testStartOne = (variables: TestStartOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.TestStartOneResponse,
    TestStartOneError,
    Schemas.TestStartOneRequest,
    {},
    {},
    TestStartOnePathParams
  >({ url: "/v2/tests/{testId}/runs", method: "post", ...variables, signal });

export type UserReadAllQueryParams = {
  email_contains?: string;
  teamId?: string[];
};

export type UserReadAllError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type UserReadAllVariables = {
  queryParams?: UserReadAllQueryParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * List all the users that can be seen by the API token.
 *
 * Require the `Read` role at the global level or on any team.
 * Require the SSO Group Mapping feature to be disabled.
 */
export const userReadAll = (variables: UserReadAllVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.UserReadAllResponse,
    UserReadAllError,
    undefined,
    {},
    UserReadAllQueryParams,
    {}
  >({ url: "/v2/users", method: "get", ...variables, signal });

export type UserCreateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type UserCreateOneVariables = {
  body: Schemas.UserRequest;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Create a new user.
 *
 * Require the `Administrate` role at the global level or on each target team.
 * Require the organization to have Custom SSO configured.
 * Require the SSO Group Mapping feature to be disabled.
 */
export const userCreateOne = (variables: UserCreateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.UserCreateOneResponse,
    UserCreateOneError,
    Schemas.UserRequest,
    {},
    {},
    {}
  >({ url: "/v2/users", method: "post", ...variables, signal });

export type UserDeleteOnePathParams = {
  /**
   * User ID
   */
  userId: string;
};

export type UserDeleteOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type UserDeleteOneVariables = {
  pathParams: UserDeleteOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Delete the specified user.
 *
 * Require the `Administrate` role at the global level.
 */
export const userDeleteOne = (variables: UserDeleteOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<undefined, UserDeleteOneError, undefined, {}, {}, UserDeleteOnePathParams>(
    { url: "/v2/users/{userId}", method: "delete", ...variables, signal }
  );

export type UserReadOnePathParams = {
  /**
   * User ID
   */
  userId: string;
};

export type UserReadOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type UserReadOneVariables = {
  pathParams: UserReadOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Get the details of the specified user.
 *
 * Require the `Read` role at the global level or on any team.
 * Require the SSO Group Mapping feature to be disabled.
 */
export const userReadOne = (variables: UserReadOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.UserReadOneResponse,
    UserReadOneError,
    undefined,
    {},
    {},
    UserReadOnePathParams
  >({ url: "/v2/users/{userId}", method: "get", ...variables, signal });

export type UserUpdateOnePathParams = {
  /**
   * User ID
   */
  userId: string;
};

export type UserUpdateOneError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.BadRequestErrorResponseContent;
    }
  | {
      status: 401;
      payload: Schemas.UnauthorizedErrorResponseContent;
    }
  | {
      status: 403;
      payload: Schemas.ForbiddenErrorResponseContent;
    }
  | {
      status: 404;
      payload: Schemas.NotFoundErrorResponseContent;
    }
  | {
      status: 409;
      payload: Schemas.ConflictErrorResponseContent;
    }
  | {
      status: 410;
      payload: Schemas.GoneErrorResponseContent;
    }
  | {
      status: 422;
      payload: Schemas.UnprocessableContentErrorResponseContent;
    }
>;

export type UserUpdateOneVariables = {
  body: Schemas.UserRequest;
  pathParams: UserUpdateOnePathParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Update the details of the specified user.
 *
 * Require the `Administrate` role at the global level or on any team.
 * Require the organization to have Custom SSO configured.
 * Require the SSO Group Mapping feature to be disabled.
 */
export const userUpdateOne = (variables: UserUpdateOneVariables, signal?: AbortSignal) =>
  gatlingEnterpriseFetch<
    Schemas.UserUpdateOneResponse,
    UserUpdateOneError,
    Schemas.UserRequest,
    {},
    {},
    UserUpdateOnePathParams
  >({ url: "/v2/users/{userId}", method: "put", ...variables, signal });

export type UploadPackageContentPathParams = {
  packageId: string;
};

export type UploadPackageContentQueryParams = {
  filename: string;
};

export type UploadPackageContentError = Fetcher.ErrorWrapper<undefined>;

export type UploadPackageContentVariables = {
  body?: Blob;
  pathParams: UploadPackageContentPathParams;
  queryParams: UploadPackageContentQueryParams;
} & GatlingEnterpriseFetcherExtraProps;

/**
 * Upload the binary content of the specified package (simulation JAR or bundle).
 *
 * Requires the `Configure` role on the package's team.
 * Requires the Managed Package feature to be enabled on the organization.
 */
export const uploadPackageContent = (
  variables: UploadPackageContentVariables,
  signal?: AbortSignal
) =>
  gatlingEnterpriseFetch<
    undefined,
    UploadPackageContentError,
    Blob,
    {},
    UploadPackageContentQueryParams,
    UploadPackageContentPathParams
  >({
    url: "/v2/packages/{packageId}/actions/upload-artifact",
    method: "post",
    ...variables,
    signal
  });

export const operationsByTag = {
  aPITokens: {
    apiTokenReadAll,
    apiTokenCreateOne,
    apiTokenDeleteOne,
    apiTokenUpdateOne,
    apiTokenRegenerate
  },
  info: { infoRead },
  locations: { locationReadAll },
  packages: {
    packageReadAll,
    packageCreateOne,
    packageDeleteOne,
    packageReadOne,
    packageUpdateOne,
    uploadPackageContent
  },
  runs: {
    runReadAll,
    runReadOne,
    runUpdateOne,
    runPublicLinkCreateOne,
    runStopOne,
    runReadLogs,
    runViewReadReportGroups,
    runViewReadReportRequests
  },
  sourceRepositories: {
    sourceRepositoryReadAll,
    sourceRepositoryCreateOne,
    sourceRepositoryDeleteOne,
    sourceRepositoryReadOne
  },
  sSOGroups: {
    ssoGroupReadAll,
    ssoGroupCreateOne,
    ssoGroupDeleteOne,
    ssoGroupReadOne,
    ssoGroupUpdateOne
  },
  teams: {
    teamReadAll,
    teamCreateOne,
    teamDeleteOne,
    teamReadOne,
    teamLimitReadOne,
    teamLimitUpdateOne
  },
  tests: {
    testReadAll,
    testCreateOne,
    testDeleteOne,
    testReadOne,
    testUpdateOne,
    testStartOne
  },
  users: {
    userReadAll,
    userCreateOne,
    userDeleteOne,
    userReadOne,
    userUpdateOne
  }
};
