/**
 * Generated by @openapi-codegen
 *
 * @version 2.0.0
 */
export type ApiTokenBriefResponse = {
  name: string;
  /**
   * @default api_token
   */
  _type: ApiTokenType & void;
  /**
   * API Token ID
   */
  _id: string;
};

export type ApiTokenCreateOneResponse = {
  data: ApiTokenDetailsResponse;
  secrets: ApiTokenSecretsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type ApiTokenDetailsResponse = {
  name: string;
  roles: ApiTokenRolesDto;
  /**
   * @default api_token
   */
  _type: ApiTokenType & void;
  /**
   * API Token ID
   */
  _id: string;
  _tokenHint: string;
  /**
   * @format date-time
   */
  _lastUsedAt?: string;
};

export type ApiTokenItemResponse = {
  name: string;
  /**
   * @default api_token
   */
  _type: ApiTokenType & void;
  /**
   * API Token ID
   */
  _id: string;
  _tokenHint: string;
  /**
   * @format date-time
   */
  _lastUsedAt?: string;
};

export type ApiTokenReadAllResponse = {
  data: ApiTokenItemResponse[];
  relatedResources: BriefResponseByResourceMap;
};

export type ApiTokenRequest = {
  name: string;
  roles: ApiTokenRolesDto;
};

export type ApiTokenRole = "reader" | "starter" | "configurer" | "administrator";

export type ApiTokenRolesDto = {
  global?: ApiTokenRole[];
  teams?: ApiTokenTeamRoleMember[];
};

export type ApiTokenSecretsResponse = {
  token: string;
};

export type ApiTokenTeamRoleMember = {
  /**
   * Team ID
   */
  id: string;
  role: ApiTokenRole;
};

export type ApiTokenUpdateOneResponse = {
  data: ApiTokenDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type BadRequestErrorResponseContent = {
  code: string;
  message: string;
  reasons?: ErrorContent[];
  values?: SimpleDictionary;
};

export type BriefResponse =
  | ApiTokenBriefResponse
  | ManagedLocationBriefResponse
  | PackageBriefResponse
  | PrivateLocationBriefResponse
  | SourceRepositoryBriefResponse
  | SsoGroupBriefResponse
  | TeamBriefResponse
  | TestBriefResponse
  | UserBriefResponse;

export type BriefResponseByResourceMap = {
  [key: string]: BriefResponse;
};

export type ConflictErrorResponseContent = {
  code: string;
  message: string;
  reasons?: ErrorContent[];
  values?: SimpleDictionary;
};

export type ErrorContent = {
  code: string;
  message: string;
  reasons?: ErrorContent[];
  values?: SimpleDictionary;
};

export type ForbiddenErrorResponseContent = {
  code: string;
  message: string;
  reasons?: ErrorContent[];
  values?: SimpleDictionary;
};

export type GoneErrorResponseContent = {
  code: string;
  message: string;
  reasons?: ErrorContent[];
  values?: SimpleDictionary;
};

export type ManagedLocationBriefResponse = {
  /**
   * @default managed_location
   */
  _type: ManagedLocationType & void;
  /**
   * Location ID
   */
  _id: string;
  /**
   * Location name
   */
  _name: string;
  /**
   * This shape is deprecated since 2026.15.0: [CLD-8183] Unused, retained for compatibility
   *
   * @deprecated true
   */
  name: string;
};

export type NotFoundErrorResponseContent = {
  code: string;
  message: string;
  reasons?: ErrorContent[];
  values?: SimpleDictionary;
};

export type PackageBriefResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * @default package
   */
  _type: PackageType & void;
  /**
   * Package ID
   */
  _id: string;
};

export type PrivateLocationBriefResponse = {
  /**
   * @default private_location
   */
  _type: PrivateLocationType & void;
  /**
   * Location ID
   */
  _id: string;
};

export type SimpleDictionary = {
  [key: string]: string;
};

export type SourceBrief = {
  type: TestTypeResponse;
};

export type SourceRepositoryBriefResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * @default source_repository
   */
  _type: SourceRepositoryType & void;
  /**
   * Source Repository ID
   */
  _id: string;
};

export type SsoGroupBriefResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * @default sso_group
   */
  _type: SsoGroupType & void;
  /**
   * The ID of the SSO group mapping
   */
  _id: string;
};

export type TeamBriefResponse = {
  /**
   * @maxLength 100
   * @minLength 1
   * @pattern ^\S(.*\S)?$
   */
  name: string;
  /**
   * @default team
   */
  _type: TeamType & void;
  /**
   * Team ID
   */
  _id: string;
};

export type TestBriefResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * @default test
   */
  _type: TestType & void;
  /**
   * Test ID
   */
  _id: string;
  source: SourceBrief;
};

export type TestTypeResponse = "build_from_sources" | "packaged" | "no_code";

export type UnauthorizedErrorResponseContent = {
  code: string;
  message: string;
  reasons?: ErrorContent[];
  values?: SimpleDictionary;
};

export type UnprocessableContentErrorResponseContent = {
  code: string;
  message: string;
  reasons?: ErrorContent[];
  values?: SimpleDictionary;
};

export type UserBriefResponse = {
  /**
   * Email address
   */
  email: string;
  /**
   * @default user
   */
  _type: UserType & void;
  /**
   * User ID
   */
  _id: string;
};

export type ApiTokenType = "api_token";

export type ManagedLocationType = "managed_location";

export type PackageType = "package";

export type PrivateLocationType = "private_location";

export type SourceRepositoryType = "source_repository";

export type SsoGroupType = "sso_group";

export type TeamType = "team";

export type TestType = "test";

export type UserType = "user";

export type InfoDataResponse = {
  versions: InfoVersionsResponse;
};

export type InfoJavaVersionResponse = {
  maximum: string;
};

export type InfoPluginVersionResponse = {
  minimum: string;
};

export type InfoPluginsVersionResponse = {
  maven: InfoPluginVersionResponse;
  sbt: InfoPluginVersionResponse;
  gradle: InfoPluginVersionResponse;
  npm: InfoPluginVersionResponse;
  bamboo: InfoPluginVersionResponse;
  jenkins: InfoPluginVersionResponse;
  teamCity: InfoPluginVersionResponse;
  githubAction: InfoPluginVersionResponse;
  ciScript: InfoPluginVersionResponse;
};

export type InfoReadResponse = {
  data: InfoDataResponse;
};

export type InfoVersionsResponse = {
  java: InfoJavaVersionResponse;
  plugins: InfoPluginsVersionResponse;
};

export type ArtifactFormatEnum = "jvm" | "js";

export type LocationCapabilitiesDto = {
  artifactFormats: ArtifactFormatEnum[];
};

export type LocationItemResponse = PrivateLocationItemResponse | ManagedLocationItemResponse;

export type LocationReadAllResponse = {
  data: LocationItemResponse[];
};

export type LocationTypeEnum = "private_location" | "managed_location";

export type ManagedLocationItemResponse = {
  /**
   * @default managed_location
   */
  _type: ManagedLocationType & void;
  /**
   * Location ID
   */
  _id: string;
  /**
   * Location name
   */
  _name: string;
  _capabilities: LocationCapabilitiesDto;
};

export type PrivateLocationItemResponse = {
  /**
   * @default private_location
   */
  _type: PrivateLocationType & void;
  /**
   * Location ID
   */
  _id: string;
  /**
   * Non-empty trimmed string
   */
  _description?: string;
  _capabilities: LocationCapabilitiesDto;
};

export type PackageArtifactChecksums = {
  md5Base64: string;
};

export type PackageArtifactDetails = {
  format: string;
  gatlingCoreVersion: string;
  filename: string;
  /**
   * @format int64
   */
  sizeBytes: number;
  checksums: PackageArtifactChecksums;
  simulations: string[];
  /**
   * @format date-time
   */
  updatedAt: string;
};

export type PackageArtifactItem = {
  format: string;
  gatlingCoreVersion: string;
};

export type PackageAssets = {
  tests: string[];
};

export type PackageCreateOneRequest = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * Team ID
   */
  teamId: string;
  storage: PackageStorageRequest;
};

export type PackageCreateOneResponse = {
  data: PackageDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type PackageDetailsResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * Team ID
   */
  teamId: string;
  /**
   * @default package
   */
  _type: PackageType & void;
  /**
   * Package ID
   */
  _id: string;
  _assets: PackageAssets;
  _storage: PackageStorageDetails;
};

export type PackageItemResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * Team ID
   */
  teamId: string;
  /**
   * @default package
   */
  _type: PackageType & void;
  /**
   * Package ID
   */
  _id: string;
  _assets: PackageAssets;
  _storage: PackageStorageItem;
};

export type PackageReadAllResponse = {
  data: PackageItemResponse[];
  relatedResources: BriefResponseByResourceMap;
};

export type PackageReadOneResponse = {
  data: PackageDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type PackageRequest = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * Team ID
   */
  teamId: string;
};

export type PackageStorageDetails =
  | (Omit<PackageStorageDetailsManaged, "type"> & {
      type: "managed";
    })
  | (Omit<PackageStorageDetailsPrivate, "type"> & {
      type: "private";
    });

export type PackageStorageDetailsManaged = PackageStorageManagedDetails &
  PackageStorageDetailsMixin;

export type PackageStorageDetailsMixin = {
  type: string;
};

export type PackageStorageDetailsPrivate = PackageStoragePrivateDetails &
  PackageStorageDetailsMixin;

export type PackageStorageItem =
  | (Omit<PackageStorageItemManaged, "type"> & {
      type: "managed";
    })
  | (Omit<PackageStorageItemPrivate, "type"> & {
      type: "private";
    });

export type PackageStorageItemManaged = PackageStorageManagedItem & PackageStorageItemMixin;

export type PackageStorageItemMixin = {
  type: string;
};

export type PackageStorageItemPrivate = PackageStoragePrivateItem & PackageStorageItemMixin;

export type PackageStorageManagedDetails = {
  artifact: PackageArtifactDetails;
};

export type PackageStorageManagedItem = {
  artifact: PackageArtifactItem;
};

export type PackageStorageManagedRequest = Record<string, any>;

export type PackageStoragePrivateDetails = {
  artifact: PackageArtifactDetails;
};

export type PackageStoragePrivateItem = {
  artifact: PackageArtifactItem;
};

export type PackageStoragePrivateRequest = Record<string, any>;

export type PackageStorageRequest =
  | (Omit<PackageStorageRequestManaged, "type"> & {
      type: "managed";
    })
  | (Omit<PackageStorageRequestPrivate, "type"> & {
      type: "private";
    });

export type PackageStorageRequestManaged = PackageStorageManagedRequest &
  PackageStorageRequestMixin;

export type PackageStorageRequestMixin = {
  type: string;
};

export type PackageStorageRequestPrivate = PackageStoragePrivateRequest &
  PackageStorageRequestMixin;

export type PackageUpdateOneResponse = {
  data: PackageDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type AssertionResponse = {
  message: string;
  succeed: boolean;
  /**
   * @format double
   */
  actualValue?: number;
};

export type DistributionDto = {
  loadGenerators: LoadGeneratorDto[];
};

export type GlobalErrorRatioCriterionDto = {
  /**
   * @format int32
   */
  timeframeInSeconds: number;
  threshold: MaxPercentageThresholdDto;
};

export type GlobalResponseTimeCriterionDto = {
  /**
   * @format int32
   */
  timeframeInSeconds: number;
  threshold: MaxMillisecondsThresholdDto;
};

export type InstanceDto = {
  /**
   * @minimum 1
   * @format int32
   */
  count: number;
};

export type LoadGeneratorDto = {
  /**
   * Location ID
   */
  locationId: string;
  instance: InstanceDto;
  /**
   * @format int32
   */
  loadPercentage?: number;
};

export type MaxMillisecondsThresholdDto = {
  /**
   * @format double
   */
  percentile: number;
  /**
   * @format int32
   */
  maxMilliseconds: number;
};

export type MaxPercentageThresholdDto = {
  /**
   * @format double
   */
  maxPercentage: number;
};

export type MeanCpuCriterionDto = {
  /**
   * @format int32
   */
  timeframeInSeconds: number;
  threshold: MaxPercentageThresholdDto;
};

export type MeaningfulTimeWindowDto = {
  /**
   * @format int32
   */
  rampUpSeconds: number;
  /**
   * @format int32
   */
  rampDownSeconds: number;
};

export type MetadataResponse = {
  /**
   * @format date-time
   */
  requestTime: string;
  query: SimpleDictionary;
};

export type Result = {
  assertions: AssertionResponse[];
};

export type RunConfigurationDetails = {
  /**
   * Test ID
   */
  testId: string;
  /**
   * @format int32
   */
  incrementalId: number;
  simulation: string;
  systemProperties: SimpleDictionary;
  environmentVariables: SimpleDictionary;
  meaningfulTimeWindow: MeaningfulTimeWindowDto;
  stopCriteria: StopCriterionDto[];
  source: SourceItem;
  distribution: DistributionDto;
};

export type RunConfigurationItem = {
  /**
   * Test ID
   */
  testId: string;
  /**
   * @format int32
   */
  incrementalId: number;
};

export type RunDetailsResponse = {
  /**
   * Non-empty trimmed string
   */
  title?: string;
  /**
   * Non-empty trimmed string
   */
  description?: string;
  /**
   * @default run
   */
  _type: RunType & void;
  /**
   * Run ID
   */
  _id: string;
  /**
   * Run status
   */
  _status: string;
  /**
   * @format date-time
   */
  _updatedAt: string;
  _startedBy?: StartedByDto;
  /**
   * @format int32
   */
  _creditsUsed: number;
  _result: Result;
  _outcome?: RunOutcomeResponse;
  _runtime: RuntimeDto;
  _configuration: RunConfigurationDetails;
};

export type RunItemResponse = {
  /**
   * Non-empty trimmed string
   */
  title?: string;
  /**
   * @default run
   */
  _type: RunType & void;
  /**
   * Run ID
   */
  _id: string;
  /**
   * Run status
   */
  _status: string;
  /**
   * @format date-time
   */
  _updatedAt: string;
  _configuration: RunConfigurationItem;
};

export type RunLogResponse = {
  /**
   * @format date-time
   */
  emittedAt: string;
  message: string;
};

export type RunOutcomeResponse = {
  successful: boolean;
};

export type RunPublicLinkCreateOneResponse = {
  url: string;
  /**
   * @format date-time
   */
  expiresAt: string;
};

export type RunPublicLinkRequest = {
  /**
   * @format int32
   */
  durationInDays: number;
};

export type RunReadAllResponse = {
  data: RunItemResponse[];
  metadata: MetadataResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type RunReadLogsResponse = {
  data: RunLogResponse[];
};

export type RunReadOneResponse = {
  data: RunDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type RunRequest = {
  /**
   * Non-empty trimmed string
   */
  title?: string;
  /**
   * Non-empty trimmed string
   */
  description?: string;
};

export type RunUpdateOneResponse = {
  data: RunDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type RuntimeDto = {
  /**
   * Package gatling version
   */
  gatlingVersion?: string;
  timeline: TimelineDto;
};

export type SourceItem = {
  type: TestTypeResponse;
};

export type StartedByApiTokenDto = {
  /**
   * API Token ID
   */
  apiTokenId: string;
};

export type StartedByDto =
  | (Omit<StartedByDtoUser, "type"> & {
      type: "user";
    })
  | (Omit<StartedByDtoApiToken, "type"> & {
      type: "apiToken";
    });

export type StartedByDtoApiToken = StartedByApiTokenDto & StartedByDtoMixin;

export type StartedByDtoMixin = {
  type: string;
};

export type StartedByDtoUser = StartedByUserDto & StartedByDtoMixin;

export type StartedByUserDto = {
  /**
   * User ID
   */
  userId: string;
};

export type StopCriterionDto =
  | (Omit<StopCriterionDtoMeanCpu, "type"> & {
      type: "meanCpu";
    })
  | (Omit<StopCriterionDtoGlobalErrorRatio, "type"> & {
      type: "globalErrorRatio";
    })
  | (Omit<StopCriterionDtoGlobalResponseTime, "type"> & {
      type: "globalResponseTime";
    });

export type StopCriterionDtoGlobalErrorRatio = GlobalErrorRatioCriterionDto & StopCriterionDtoMixin;

export type StopCriterionDtoGlobalResponseTime = GlobalResponseTimeCriterionDto &
  StopCriterionDtoMixin;

export type StopCriterionDtoMeanCpu = MeanCpuCriterionDto & StopCriterionDtoMixin;

export type StopCriterionDtoMixin = {
  type: string;
};

export type TimelineDto = {
  build?: TimelineStepDto;
  deploy?: TimelineStepDto;
  inject?: TimelineStepDto;
};

export type TimelineStepDto = {
  /**
   * @format date-time
   */
  startedAt: string;
  /**
   * @format date-time
   */
  endedAt: string | null;
};

export type RunType = "run";

export type RunViewCountDto = {
  /**
   * @format int64
   */
  sent: number;
  result: RunViewResultDto;
};

export type RunViewGroupCountDto = {
  result: RunViewResultDto;
};

export type RunViewGroupNodeDto = {
  name: string;
  count: RunViewCountDto;
  responseTimeInMs?: RunViewResponseTimeInMsDto;
  children: RunViewNodeDto[];
};

export type RunViewGroupNodeType = "group";

/**
 * A group of the run. The tree is homogeneous: every node is a group, and its
 * `children` are its sub-groups.
 */
export type RunViewGroupReportNodeDto = {
  type: RunViewGroupNodeType;
  name: string;
  count: RunViewGroupCountDto;
  cumulatedResponseTimeInMs?: RunViewResponseTimeInMsDto;
  executionTimeInMs?: RunViewResponseTimeInMsDto;
  children: RunViewGroupReportNodeDto[];
};

export type RunViewNodeDto =
  | (Omit<RunViewNodeDtoRequestGroup, "type"> & {
      type: "request_group";
    })
  | (Omit<RunViewNodeDtoRequest, "type"> & {
      type: "request";
    });

export type RunViewNodeDtoMixin = {
  type: string;
};

export type RunViewNodeDtoRequest = RunViewRequestLeafDto & RunViewNodeDtoMixin;

export type RunViewNodeDtoRequestGroup = RunViewGroupNodeDto & RunViewNodeDtoMixin;

export type RunViewReadReportGroupsMetadataDto = {
  /**
   * @format date-time
   */
  requestTime: string;
  query: RunViewReadReportGroupsQueryDto;
};

export type RunViewReadReportGroupsQueryDto = {
  /**
   * @format int32
   */
  from: number;
  /**
   * @format int32
   */
  to: number;
  /**
   * Name of the scenario
   */
  scenario?: string;
};

export type RunViewReadReportGroupsResponse = {
  data: RunViewGroupReportNodeDto[];
  metadata: RunViewReadReportGroupsMetadataDto;
};

export type RunViewReadReportRequestsMetadataDto = {
  /**
   * @format date-time
   */
  requestTime: string;
  query: RunViewReadReportRequestsQueryDto;
};

export type RunViewReadReportRequestsQueryDto = {
  /**
   * @format int32
   */
  from: number;
  /**
   * @format int32
   */
  to: number;
  /**
   * Name of the scenario
   */
  scenario?: string;
};

export type RunViewReadReportRequestsResponse = {
  data: RunViewReportDataDto;
  metadata: RunViewReadReportRequestsMetadataDto;
};

/**
 * The report root aggregates every request in the run, or only those of the
 * `scenario` query parameter when it is set. Its children are the run's
 * top-level groups and ungrouped requests.
 */
export type RunViewReportDataDto = {
  type: RunViewReportType;
  count: RunViewCountDto;
  responseTimeInMs?: RunViewResponseTimeInMsDto;
  children: RunViewNodeDto[];
};

export type RunViewReportType = "report";

export type RunViewRequestLeafDto = {
  name: string;
  count: RunViewCountDto;
  responseTimeInMs?: RunViewResponseTimeInMsDto;
};

export type RunViewResponseTimeInMsDto = {
  /**
   * @format int64
   */
  mean: number;
  /**
   * @format int64
   */
  standardDeviation: number;
  /**
   * @format int64
   */
  min: number;
  /**
   * @format int64
   */
  p25: number;
  /**
   * @format int64
   */
  p50: number;
  /**
   * @format int64
   */
  p75: number;
  /**
   * @format int64
   */
  p80: number;
  /**
   * @format int64
   */
  p85: number;
  /**
   * @format int64
   */
  p90: number;
  /**
   * @format int64
   */
  p95: number;
  /**
   * @format int64
   */
  p99: number;
  /**
   * 99.9th percentile
   *
   * @format int64
   */
  p999: number;
  /**
   * 99.99th percentile
   *
   * @format int64
   */
  p9999: number;
  /**
   * @format int64
   */
  max: number;
};

export type RunViewResultDto = {
  /**
   * @format int64
   */
  ok: number;
  /**
   * @format int64
   */
  ko: number;
};

export type Remote = {
  /**
   * Non-empty trimmed string
   */
  url: string;
};

export type SourceRepositoryAssets = {
  tests: string[];
};

export type SourceRepositoryCreateOneResponse = {
  data: SourceRepositoryDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type SourceRepositoryDetailsResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * Team ID
   */
  teamId: string;
  remote: Remote;
  /**
   * @default source_repository
   */
  _type: SourceRepositoryType & void;
  /**
   * Source Repository ID
   */
  _id: string;
  _assets: SourceRepositoryAssets;
};

export type SourceRepositoryItemResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * @default source_repository
   */
  _type: SourceRepositoryType & void;
  /**
   * Source Repository ID
   */
  _id: string;
};

export type SourceRepositoryReadAllResponse = {
  data: SourceRepositoryItemResponse[];
  relatedResources: BriefResponseByResourceMap;
};

export type SourceRepositoryReadOneResponse = {
  data: SourceRepositoryDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type SourceRepositoryRequest = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * Team ID
   */
  teamId: string;
  remote: Remote;
};

export type SsoGroupCreateOneResponse = {
  data: SsoGroupDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type SsoGroupDetailsResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  roles: UserRolesDto;
  /**
   * @default sso_group
   */
  _type: SsoGroupType & void;
  /**
   * The ID of the SSO group mapping
   */
  _id: string;
};

export type SsoGroupItemResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  roles: UserRolesDto;
  /**
   * @default sso_group
   */
  _type: SsoGroupType & void;
  /**
   * The ID of the SSO group mapping
   */
  _id: string;
};

export type SsoGroupReadAllResponse = {
  data: SsoGroupItemResponse[];
  relatedResources: BriefResponseByResourceMap;
};

export type SsoGroupReadOneResponse = {
  data: SsoGroupDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type SsoGroupRequest = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  roles: UserRolesDto;
};

export type SsoGroupUpdateOneResponse = {
  data: SsoGroupDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type TeamRoleDto = {
  /**
   * Team ID
   */
  id: string;
  role: UserRoleV2Enum;
};

export type UserRoleV2Enum = "administrator" | "leader" | "tester" | "contributor" | "viewer";

export type UserRolesDto = {
  global?: UserRoleV2Enum[];
  teams?: TeamRoleDto[];
};

export type ApiToken = {
  /**
   * API Token ID
   */
  id: string;
  role: ApiTokenRole;
};

export type Credits = {
  /**
   * @minimum 0
   * @format int32
   */
  quota: number;
};

export type Members = {
  users: User[];
  apiTokens: ApiToken[];
  ssoGroups: SsoGroup[];
};

export type SsoGroup = {
  /**
   * The ID of the SSO group mapping
   */
  id: string;
  role: UserRoleV2Enum;
};

export type TeamAssets = {
  tests: string[];
  packages: string[];
  sourceRepositories: string[];
};

export type TeamCreateOneResponse = {
  data: TeamDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type TeamDetailsResponse = {
  /**
   * @maxLength 100
   * @minLength 1
   * @pattern ^\S(.*\S)?$
   */
  name: string;
  /**
   * @default team
   */
  _type: TeamType & void;
  /**
   * Team ID
   */
  _id: string;
  _limits: TeamLimits;
  /**
   * @format int32
   */
  _creditsUsed: number;
  _members: Members;
  _assets: TeamAssets;
};

export type TeamItemResponse = {
  /**
   * @maxLength 100
   * @minLength 1
   * @pattern ^\S(.*\S)?$
   */
  name: string;
  /**
   * @default team
   */
  _type: TeamType & void;
  /**
   * Team ID
   */
  _id: string;
  _limits: TeamLimits;
  /**
   * @format int32
   */
  _creditsUsed: number;
};

export type TeamLimitReadOneResponse = {
  data: TeamLimitResponse;
};

export type TeamLimitRequest = {
  credits?: Credits;
};

export type TeamLimitResponse = {
  credits?: Credits;
};

export type TeamLimitUpdateOneResponse = {
  data: TeamLimitResponse;
};

export type TeamLimits = {
  credits?: Credits;
};

export type TeamReadAllResponse = {
  data: TeamItemResponse[];
  relatedResources: BriefResponseByResourceMap;
};

export type TeamReadOneResponse = {
  data: TeamDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type TeamRequest = {
  /**
   * @maxLength 100
   * @minLength 1
   * @pattern ^\S(.*\S)?$
   */
  name: string;
};

export type User = {
  /**
   * User ID
   */
  id: string;
  role: UserRoleV2Enum;
};

export type BuildCommandDto =
  | (Omit<BuildCommandDtoMaven, "type"> & {
      type: "maven";
    })
  | (Omit<BuildCommandDtoMavenWrapper, "type"> & {
      type: "maven-wrapper";
    })
  | (Omit<BuildCommandDtoGradle, "type"> & {
      type: "gradle";
    })
  | (Omit<BuildCommandDtoGradleWrapper, "type"> & {
      type: "gradle-wrapper";
    })
  | (Omit<BuildCommandDtoSbt, "type"> & {
      type: "sbt";
    })
  | (Omit<BuildCommandDtoNpm, "type"> & {
      type: "npm";
    })
  | (Omit<BuildCommandDtoCustom, "type"> & {
      type: "custom";
    });

export type BuildCommandDtoCustom = CustomCommand & BuildCommandDtoMixin;

export type BuildCommandDtoGradle = DefaultCommand & BuildCommandDtoMixin;

export type BuildCommandDtoGradleWrapper = DefaultCommand & BuildCommandDtoMixin;

export type BuildCommandDtoMaven = DefaultCommand & BuildCommandDtoMixin;

export type BuildCommandDtoMavenWrapper = DefaultCommand & BuildCommandDtoMixin;

export type BuildCommandDtoMixin = {
  type: string;
};

export type BuildCommandDtoNpm = DefaultCommand & BuildCommandDtoMixin;

export type BuildCommandDtoSbt = DefaultCommand & BuildCommandDtoMixin;

export type BuildFromSource = {
  /**
   * Source Repository ID
   */
  sourceRepositoryId: string;
  buildTool: BuildCommandDto;
  /**
   * Simulation class name
   */
  simulation: string;
  workingDirectory?: string;
  branch?: string;
};

export type CustomCommand = {
  command: string;
  /**
   * Package format
   */
  packageFormat: string;
};

export type DefaultCommand = Record<string, any>;

export type ExecutionDto = {
  meaningfulTimeWindow: MeaningfulTimeWindowDto;
  systemProperties: SimpleDictionary;
  environmentVariables: SimpleDictionary;
  /**
   * @default false
   */
  ignoreGlobalProperties: boolean;
  stopCriteria: StopCriterionDto[];
};

export type NoCode = {
  /**
   * Team ID
   */
  teamId: string;
};

export type Packaged = {
  /**
   * Package ID
   */
  packageId: string;
  /**
   * Simulation class name
   */
  simulation: string;
};

export type SourceDetails =
  | (Omit<SourceDetailsBuildFromSources, "type"> & {
      type: "build_from_sources";
    })
  | (Omit<SourceDetailsPackaged, "type"> & {
      type: "packaged";
    })
  | (Omit<SourceDetailsNoCode, "type"> & {
      type: "no_code";
    });

export type SourceDetailsBuildFromSources = BuildFromSource & SourceDetailsMixin;

export type SourceDetailsMixin = {
  type: string;
};

export type SourceDetailsNoCode = NoCode & SourceDetailsMixin;

export type SourceDetailsPackaged = Packaged & SourceDetailsMixin;

export type TestCreateOneResponse = {
  data: TestDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type TestDetailsResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  distribution: DistributionDto;
  execution: ExecutionDto;
  source: SourceDetails;
  /**
   * @default test
   */
  _type: TestType & void;
  /**
   * Test ID
   */
  _id: string;
  /**
   * Team ID
   */
  _teamId: string;
  /**
   * @format date-time
   */
  _updatedAt: string;
};

export type TestItemResponse = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  /**
   * @default test
   */
  _type: TestType & void;
  /**
   * Test ID
   */
  _id: string;
  /**
   * Team ID
   */
  _teamId: string;
  /**
   * @format date-time
   */
  _updatedAt: string;
  source: SourceItem;
};

export type TestReadAllResponse = {
  data: TestItemResponse[];
  metadata: TestReadAllResponseMetadata;
  relatedResources: BriefResponseByResourceMap;
};

export type TestReadAllResponseMetadata = {
  /**
   * @format date-time
   */
  requestTime: string;
};

export type TestReadOneResponse = {
  data: TestDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type TestRequest = {
  /**
   * Non-empty trimmed string
   */
  name: string;
  distribution: DistributionDto;
  execution: ExecutionDto;
  source: SourceDetails;
};

export type TestStartOneExtra = {
  systemProperties?: SimpleDictionary;
  environmentVariables?: SimpleDictionary;
};

export type TestStartOneMetadataResponse = {
  urls: TestStartOneMetadataUrlsResponse;
};

export type TestStartOneMetadataUrlsResponse = {
  run: string;
};

export type TestStartOneRequest = {
  /**
   * Non-empty trimmed string
   */
  title?: string;
  /**
   * Non-empty trimmed string
   */
  description?: string;
  extra?: TestStartOneExtra;
};

export type TestStartOneResponse = {
  data: RunDetailsResponse;
  metadata: TestStartOneMetadataResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type TestUpdateOneResponse = {
  data: TestDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type UserCreateOneResponse = {
  data: UserDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type UserDetailsResponse = {
  /**
   * Email address
   */
  email: string;
  roles: UserRolesDto;
  /**
   * PersonName
   *
   * @pattern ^[^<>&"\v$%!#?§;*~/\\|^=\[\]{}()\p{Cntrl}]+$
   */
  firstName: string;
  /**
   * PersonName
   *
   * @pattern ^[^<>&"\v$%!#?§;*~/\\|^=\[\]{}()\p{Cntrl}]+$
   */
  lastName: string;
  /**
   * @default user
   */
  _type: UserType & void;
  /**
   * User ID
   */
  _id: string;
};

export type UserItemResponse = {
  /**
   * Email address
   */
  email: string;
  roles: UserRolesDto;
  /**
   * PersonName
   *
   * @pattern ^[^<>&"\v$%!#?§;*~/\\|^=\[\]{}()\p{Cntrl}]+$
   */
  firstName: string;
  /**
   * PersonName
   *
   * @pattern ^[^<>&"\v$%!#?§;*~/\\|^=\[\]{}()\p{Cntrl}]+$
   */
  lastName: string;
  /**
   * @default user
   */
  _type: UserType & void;
  /**
   * User ID
   */
  _id: string;
};

export type UserReadAllResponse = {
  data: UserItemResponse[];
  relatedResources: BriefResponseByResourceMap;
};

export type UserReadOneResponse = {
  data: UserDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};

export type UserRequest = {
  /**
   * Email address
   */
  email: string;
  roles: UserRolesDto;
  /**
   * PersonName
   *
   * @pattern ^[^<>&"\v$%!#?§;*~/\\|^=\[\]{}()\p{Cntrl}]+$
   */
  firstName: string;
  /**
   * PersonName
   *
   * @pattern ^[^<>&"\v$%!#?§;*~/\\|^=\[\]{}()\p{Cntrl}]+$
   */
  lastName: string;
};

export type UserUpdateOneResponse = {
  data: UserDetailsResponse;
  relatedResources: BriefResponseByResourceMap;
};
