name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "version number (e.g. '1.2.3')"

permissions:
  id-token: write
  contents: none # As we'll use another token anyway

defaults:
  run:
    shell: bash

env:
  VERSION: ${{ inputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate version number
        run: |
          echo "${VERSION}" | grep -P '^[0-9]+\.[0-9]+\.[0-9]+$'

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GATLING_CI_TOKEN }} # To create release commit and tag

      # Build and publish to npmjs

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          package-manager-cache: false
          registry-url: https://registry.npmjs.org

      - name: Update npm
        run: npm install -g npm@latest

      - name: Npm build and release
        working-directory: ./mcp-servers/gatling
        run: |
          npm version "$VERSION"
          npm ci
          npm run format-check
          npm run build
          npm publish --access=public

      # Build and publish Docker image

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c # v4.5.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./mcp-servers/gatling
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            gatlingcorp/gatling-mcp-server:${{ env.VERSION }}
            gatlingcorp/gatling-mcp-server:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: gatlingcorp/gatling-mcp-server
          short-description: MCP server to bridge AI applications with Gatling Enterprise
          readme-filepath: ./mcp-servers/gatling/README.md

      # Update marketplace files and tag

      - name: Edit marketplace plugin version
        env:
          GIT_USER_NAME: ${{ secrets.GATLING_CI_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GATLING_CI_EMAIL }}
        run: |
          contents=$(jq ".version = \"$VERSION\"" plugins/gatling/.claude-plugin/plugin.json) && \
          echo -E "$contents" > plugins/gatling/.claude-plugin/plugin.json
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
          git commit --all --message "chore: set plugin version to $VERSION"
          git tag "v$VERSION" --message "Version v$VERSION"
          git push origin
          git push origin "v$VERSION"
